force-app/main/default/objects/ExpenseItem__c/ExpenseItem__c.object-meta.xml
<CustomObject>
    <label>Expense Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpenseItem__c/fields/Expense_Item_Category__c.field-meta.xml
<CustomField>
    <fullName>Expense_Item_Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Office Supplies</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PieChartController.cls
public class PieChartController {   
    @AuraEnabled(cacheable=true)
    public static List<DataSet> getTotalExpenseByCategory(){
        List<AggregateResult> result =  [Select Expense_Item_Category__c category, sum(Amount__c) totalAmount from ExpenseItem__c GROUP BY Expense_Item_Category__c ORDER BY Expense_Item_Category__c];
        List<DataSet> dataSet = new List<DataSet>();
        for(AggregateResult ar:result){
            String category =  (String)ar.get('category') ;
            Decimal totalAmount =(Decimal)ar.get('totalAmount'); 
            dataSet.add(new DataSet(category ,totalAmount));
        }
        return dataSet ; 
    }
    
    public class DataSet{
        public DataSet(String category ,Decimal totalAmount){
            this.category  = category ; 
            this.totalAmount = totalAmount ;
        }
        @AuraEnabled
        public String category {get;set;}
        @AuraEnabled
        public Decimal totalAmount {get;set;}   
    }    
}