force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Expense Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Expense_Date__c.field-meta.xml
<CustomField>
    <fullName>Expense_Date__c</fullName>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <summarizedField>ExpenseItem__c.Amount__c</summarizedField>
    <summaryForeignKey>ExpenseItem__c.Expense__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/LineChartController.cls
public class LineChartController {   
    @AuraEnabled(cacheable=true)
    public static List<DataSet> getTotalExpenseByMonth(){
        List<AggregateResult> result =  [Select calendar_month(Expense_Date__c) month, sum(Total_Amount__c) totalAmount from Expense__c GROUP BY calendar_month(Expense_Date__c) ORDER BY calendar_month(Expense_Date__c) ASC ];
        List<DataSet> dataSet = new List<DataSet>();
        for(AggregateResult ar:result){
            Integer month =  (Integer)ar.get('month') ;
            Decimal totalAmount =(Decimal)ar.get('totalAmount'); 
            dataSet.add(new DataSet(month ,totalAmount));
        }
        return dataSet ; 
    }
    
    public class DataSet{
        public DataSet(Integer month ,Decimal totalAmount){
            this.month  = month ; 
            this.totalAmount = totalAmount ;
        }
        @AuraEnabled
        public Integer month {get;set;}
        @AuraEnabled
        public Decimal totalAmount {get;set;}   
    }    
}