force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Expense Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Expense_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Expense_Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
                <default>true</default>
                <label>Not Submitted</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Expense_Date__c.field-meta.xml
<CustomField>
    <fullName>Expense_Date__c</fullName>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Item__c/Expense_Item__c.object-meta.xml
<CustomObject>
    <label>Expense Item</label>
    <nameField>
        <label>Expense Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Item__c/fields/Expense__c.field-meta.xml
<CustomField>
    <fullName>Expense__c</fullName>
    <label>Expense</label>
    <referenceTo>Expense__c</referenceTo>
    <relationshipLabel>Expense Items</relationshipLabel>
    <relationshipName>Expense_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Expense_Item__c/fields/Expense_Item_Amount__c.field-meta.xml
<CustomField>
    <fullName>Expense_Item_Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense_Item__c/fields/Expense_Item_Category__c.field-meta.xml
<CustomField>
    <fullName>Expense_Item_Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Entertainment</fullName>
            </value>
            <value>
                <fullName>Fees</fullName>
            </value>
            <value>
                <fullName>HR Services</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Meals</fullName>
            </value>
            <value>
                <fullName>Meetings and Events</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Real Estate &amp; Facilities</fullName>
            </value>
            <value>
                <fullName>Technology</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
            <value>
                <fullName>Travel Expenses</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense_Item__c/fields/Expense_Item_Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Expense_Item_Transaction_Date__c</fullName>
    <label>Transaction Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense_Vendor__c/Expense_Vendor__c.object-meta.xml
<CustomObject>
    <label>Expense Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Vendors</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor__c/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <label>Vendor</label>
</RecordType>

force-app/main/default/classes/LineChartControllerTestSuite.cls
@isTest
public class LineChartControllerTestSuite {
	static testMethod void testGetTotalExpenseByMonth() {
        //Insert 3 Expenses totalling $2150.44 for this month
        Expense_Vendor__c vendor = new Expense_Vendor__c(Name='Test Vendor');
		insert vendor;

		Expense__c e1 = new Expense__c(Vendor__c=vendor.Id, Name='Expense 1', Expense_Approval_Status__c = 'Approved', Expense_Date__c=Date.today());
		insert e1;
		Expense_Item__c i1 = new Expense_Item__c(Expense__c=e1.Id, Name='Item 1', Expense_Item_Transaction_Date__c=Date.today(), Expense_Item_Category__c='Fees', Expense_Item_Amount__c=100.00);
		insert i1;
        
        Expense__c e2 = new Expense__c(Vendor__c=vendor.Id, Name='Expense 2', Expense_Approval_Status__c = 'Approved', Expense_Date__c=Date.today());
		insert e2;
		Expense_Item__c i2 = new Expense_Item__c(Expense__c=e2.Id, Name='Item 2', Expense_Item_Transaction_Date__c=Date.today(), Expense_Item_Category__c='Entertainment', Expense_Item_Amount__c=950.45);
		insert i2;
        
        Expense__c e3 = new Expense__c(Vendor__c=vendor.Id, Name='Expense 3', Expense_Approval_Status__c = 'Approved', Expense_Date__c=Date.today());
		insert e3;
		Expense_Item__c i3 = new Expense_Item__c(Expense__c=e3.Id, Name='Item 3', Expense_Item_Transaction_Date__c=Date.today(), Expense_Item_Category__c='Meetings and Events', Expense_Item_Amount__c=1099.99);
		insert i3;
        
        List<LineChartController.DataSet> result = LineChartController.getTotalExpenseByMonth();
        System.assertEquals(1, result.size(), 'There should only be 1 month worth of expenses in the result');
        System.assertEquals(Date.today().month(), result.get(0).month, 'Unexpected month');
        System.assertEquals(2150.44, result.get(0).totalAmount, 'Unexpected total amount');
    }
}